version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  heroku_deployment:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                main