# Generated by Django 3.2.6 on 2021-08-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_game_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='has_extendion',
            new_name='has_extension',
        ),
        migrations.RemoveField(
            model_name='game',
            name='distributor',
        ),
        migrations.RemoveField(
            model_name='game',
            name='editor',
        ),
        migrations.AddField(
            model_name='game',
            name='editor',
            field=models.ManyToManyField(to='blog.Editor'),
        ),
        migrations.DeleteModel(
            name='Distributor',
        ),
    ]
