# Generated by Django 3.2.6 on 2021-08-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210826_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='editor',
            name='web_site',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
