# Generated by Django 3.2.6 on 2021-08-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210826_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='illustrator',
        ),
    ]
