# Generated by Django 3.2.6 on 2021-08-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='nationality',
        ),
        migrations.AlterField(
            model_name='game',
            name='language',
            field=models.CharField(blank=True, choices=[('fr', 'Francais'), ('en', 'Anglais')], max_length=150),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
